pipeline:
  clone:
    image: plugins/git
    recursive: false
    volumes:
      - /data/git/digipost-api-client-java/.git:/drone/src/github.com/digipost/digipost-api-client-java/.git
  build:
    image: digipost/docker-maven:3.3.9-jdk-8
    volumes:
      - /data/maven:/home/maven/.m2
      - /data/git/digipost-api-client-java/.git:/drone/src/github.com/digipost/digipost-api-client-java/.git
    commands:
      - export WORKSPACE=$(pwd)
      - chown maven:maven ${WORKSPACE}
      - chown -R maven:maven ${WORKSPACE}/*
      - export HOME=/home/maven
      - export USER=maven
      - export DPOST_HOME=/tmp
      - export LOGFOLDER=/tmp
      - su -p maven -c "mvn clean deploy -V -B"
