//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.31 at 02:16:15 PM CET 
//

package no.digipost.api.client.representations;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "message-base", propOrder = { "messageId", "senderId", "preEncrypt" })
public class MessageBase extends Representation {

	@XmlElement(required = true)
	protected String messageId;
	protected Long senderId;
	protected Boolean preEncrypt;

	MessageBase() {
	}

	public MessageBase(final String messageId, final Link[] links) {
		super(links);
		this.messageId = messageId;
	}

	public String getMessageId() {
		return messageId;
	}

	public void setMessageId(final String messageId) {
		this.messageId = messageId;
	}

	public Long getSenderId() {
		return senderId;
	}

	public void setSenderId(final Long senderId) {
		this.senderId = senderId;
	}

	public void setPreEncrypt(final Boolean preEncrypt) {
		this.preEncrypt = preEncrypt;
	}

	public boolean skalPrekrypteres() {
		return preEncrypt != null && preEncrypt;
	}

	public Link getSelfLink() {
		return getLinkByRelationName(Relation.SELF);
	}

	public Link getFileLink() {
		return getLinkByRelationName(Relation.ADD_CONTENT_AND_SEND);
	}

	public Link getEncryptionKeyLink() {
		return getLinkByRelationName(Relation.GET_ENCRYPTION_KEY);
	}

}
