# name of the software
title: Digipost API client library for Java
# current version of the software
version: 1.0
# licence of the software
license: Apache License, version 2.0
licenseUrl: http://www.apache.org/licenses/LICENSE-2.0

baseurl: "/digipost-api-client-java"

currentVersion: "16.x"
versions: ["16.x", "15.x", "13.x", "11.x", "10.x", "9.0", "8.0"]
deprecatedVersions: ["8.0", "9.0", "10.x", "11.x", "13.x"]

collections:
  v8_0:
    output: true
    permalink: /v8.0/
  v9_0:
    output: true
    permalink: /v9.0/
  v10_x:
    output: true
    permalink: /v10.x/
  v11_x:
    output: true
    permalink: /v11.x/
  v13_x:
    output: true
    permalink: /v13.x/
  v15_x:
    output: true
    permalink: /v15.x/
  v16_x:
    output: true
    permalink: /v16.x/

# list of additional links on the right of the top menu
headerLinks:
  - title: Download library
    url: https://search.maven.org/artifact/no.digipost/digipost-api-client-java
  - title: GitHub
    url: https://github.com/digipost/digipost-api-client-java
  - title: Digipost
    url: https://www.digipost.no

# list of additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/digipost/digipost-api-client-java
  - title: Issues
    url: https://github.com/digipost/digipost-api-client-java/issues

# header
header:
  color1: "#e32d22"
  color2:
  trianglify: false

# github buttons
githubButton:
  user: digipost
  repo: digipost-api-client-java

# DON'T MODIFY
highlight: rouge

github: [metadata]

plugins:
  - jekyll-redirect-from

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']
