source 'https://rubygems.org'

require 'json'
require 'open-uri'
versions = JSON.parse(OpenURI.open_uri('https://pages.github.com/versions.json').read)

gem 'github-pages', versions['github-pages'], group: :jekyll_plugins
gem 'activesupport', '~> 7.1', '>= 7.1.3'
gem "webrick", "~> 1.8"
